### PR TITLE
fix: Update spelling of suppressed

### LINKED ISSUE #1060: Supress Log Color is misspelt
The property and English language value in "Supress Log Color" should be spelt "**Suppress** Log Color"

### PR DESCRIPTION
**Pull request by jsa34**
Previously wrongly spelt as supressed

Fixes #1060

### CODE REVIEW

**Comment by jsa34** [comment]
Not sure what it means: Pending — add a semantic commit or PR title ?

**Comment by jsa34** [comment]
Silly me - found the answer.... :S

**Comment by mykola-mokhnach** [comment]
You don't need to change localized resources. It would be enough to only update the English one. We have the automated script, which is going to sync other locales as soon as the PR for the English one is merged

**Comment by jsa34** [comment]
Ah - good to know!  Do I need to amend PR?

**Comment by mykola-mokhnach** [comment]
> Do I need to amend PR?

No need, we anyway squash the stuff before merging it to master

**Comment by jsa34** [comment]
Fab - thanks :)

**Pull request merged**
