### PR TITLE
WIP: Testing still... Revert "Get source, screenshot and windowSize concurrently"

### PR DESCRIPTION
**Pull request by dpgraham**
Reverts appium/appium-desktop#916

Causing race conditions that cause the spinner to act indefinitely

### CODE REVIEW

**Comment by dpgraham** [comment]
This doesn't fix the issue.

**Comment by vijayqaguy** [comment]
@dpgraham I am just providing more information to narrow down this issue. It works perfectly fine on v1.12.0 but not on v1.12.1. We just need to compare the changes done between these versions. I am trying from my side as well.

**Comment by danieltg** [comment]
@dpgraham I've just tried it now and Perfecto cloud provider run properly after reverting commit #916 back.

**Comment by danieltg** [comment]
@dpgraham Can you kindly retry the revert as per our testing it does fix the issue - at least for Perfecto cloud provider.

**Comment by dpgraham** [comment]
@danieltg I don't have time, but I'll just leave this as-is until I get around to it again

**Pull request closed without merging**
