### PR TITLE
Using Appium server 1.11.1

### PR DESCRIPTION
**Pull request by budtmo**

### CODE REVIEW

**Comment by dpgraham** [comment]
Thanks! I can merge this after you've signed the CLA... and also can you bump up to 1.11.1?

**Comment by budtmo** [comment]
@dpgraham I have already signed the CLA, but it seems that the build in azure pipeline fails. could you maybe take a look what is missing?

**Comment by dpgraham** [comment]
@budtmo can you run `npm install` from your branch. That should update `package-lock.json` which needs to be committed and pushed.

**Comment by budtmo** [comment]
@dpgraham yes, I will do it tomorrow then

**Comment by budtmo** [comment]
@dpgraham done

**Pull request merged**
