### PR TITLE
Use env variables for SauceLabs and TO

### PR DESCRIPTION
**Pull request by dpgraham**
* If no sauce username or key provided, use what's in env variables
* If no TestObject host provided or TestObject key use what's in env variables

(reviewer: @jlipps)

### CODE REVIEW

**Comment by dpgraham** [comment]
That's right, yes.

**Comment by jlipps** [comment]
Just wondering about the UX of this. What about this thought: if we _are_ going to end up using the env vars (i.e., will not use something the user has typed in because they didn't type anything in, and we found environment variables with the appropriate names), can we adjust the placeholder text to reflect this? something like `Using data found in $SAUCE_ACCESS_KEY`?

**Comment by dpgraham** [comment]
Yeah I think that's a good idea. If they have the env set show a placeholder. I'll make that change.

**Comment by dpgraham** [comment]
Pushed a change

**Pull request merged**
