### PR TITLE
Localize the rest of the application resources

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
@dpgraham Could you please help with texting? Simply go through all possible application dialogs and make sure there are no new errors in the console. Thanks in advance

### CODE REVIEW

**Comment by dpgraham** [comment]
Sure, I'll look at that today.

**Comment by dpgraham** [comment]
Looks good to me. I didn't see any console errors.

**Comment by mykola-mokhnach** [comment]
Cool thanks. So shall I merge it to master?

**Comment by dpgraham** [comment]
Yes you can.

**Pull request merged**
