### PR TITLE
Adding Korean translation

### PR DESCRIPTION
**Pull request by stevechun**
Added Korean translation for the app 🇰🇷

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
Thanks @stevechun

**Comment by KazuCocoa** [comment]
Thanks!, but can you add the localised resources in https://crowdin.com/project/appium-desktop ?
https://github.com/appium/appium-desktop/blob/master/CONTRIBUTING.md#localization

**Comment by dpgraham** [comment]
@mykola-mokhnach does the synchronization work both ways (updating the JSON updates Crowdin) or do we need to copy-paste these translations?

**Comment by mykola-mokhnach** [comment]
@dpgraham Only changes in the original (English) json get propagated to Crowdin. Downloaded files though contain all other available locales.

**Comment by dpgraham** [comment]
@mykola-mokhnach okay, so we'll need to update Crowdin with the Korean translations.

**Comment by mykola-mokhnach** [comment]
@dpgraham Crowdin has import feature. You can simply download the translated json file and select `Import` for the corresponding language to add translated resources from the file(s) into the TMS

**Pull request merged**
