### PR TITLE
Building with platform in output package filenames

### PR DESCRIPTION
**Pull request by iammike**
Tried doing this at a level above the platforms, but `${platform}` comes back as 'darwin' for all platforms since it isn't in the platform specific block at the time the substitution is made.

### CODE REVIEW

**Comment by dpgraham** [comment]
Do you mind opening an issue to go along with this? I'd like to know what problem this is solving and have a GitHub issue that I can link in the release notes if we merge this into a future release.

**Comment by iammike** [comment]
Issue is referenced above - #797

**Comment by iammike** [comment]
`npm run package-all` output in `release` dir:

```Appium-1.10.0-mac.zip
Appium-linux-1.10.0.AppImage*
Appium-mac-1.10.0.dmg
Appium-mac-1.10.0.dmg.blockmap
Appium-windows-1.10.0.exe
Appium-windows-1.10.0.exe.blockmap
builder-effective-config.yaml
latest-linux.yml
latest-mac.yml
latest.yml
linux-unpacked/
mac/
win-unpacked/
```

**Comment by dpgraham** [comment]
Looks good. I'll need to test it to make sure it does not break our auto updater. But I can accept this.

**Comment by dpgraham** [comment]
Thanks for this. This looks a lot better! Less confusing.

**Pull request merged**
