### PR TITLE
add strictSSL option

### PR DESCRIPTION
**Pull request by KazuCocoa**
For https://github.com/appium/appium-desktop/issues/1603 with WDIO update

### CODE REVIEW

**Comment by KazuCocoa** [comment]
A new web2driver with webdriverio https://github.com/KazuCocoa/web2driver/tree/update-wdio , an error blocked to render the inspector view correctly. I must dig into it further..

**Comment by huzaifaiftikhar** [comment]
@KazuCocoa Are you still working on this? If not, can you share more details/stacktraces/screenshots on what errors you were encountering after using the branch of `web2driver` with the updated `webdriverio`?

**Comment by KazuCocoa** [comment]
Yes, but currently, this PR is pending since we cannot update webdriverio. I mean `npm install` fails in some new version since the current webdriverio.

**Comment by huzaifaiftikhar** [comment]
> Yes, but currently, this PR is pending since we cannot update webdriverio. I mean `npm install` fails in some new version since the current webdriverio.

Ohh I get it. Will this be a blocker for future Appium Desktop releases?

**Comment by KazuCocoa** [comment]
Could be for master branch.

For now, I picked critical/important changes to https://github.com/appium/appium-desktop/tree/1.20 (for 1.20) from master as a workaround. The release cycle is almost the same as appium itself.

**Comment by huzaifaiftikhar** [comment]
> Could be for master branch.
> 
> For now, I picked critical/important changes to https://github.com/appium/appium-desktop/tree/1.20 (for 1.20) from master as a workaround. The release cycle is almost the same as appium itself.

Ohh I was unaware of this and thought we create the release branches from the master, I created a PR #1691 for master, I think I should create that PR against the 1.20 branch then so that it gets released with AD v1.20?

**Comment by jlipps** [comment]
closing as this change would now need to be applied to the inspector repo

**Pull request closed without merging**
